### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Yu-python** [FioraLove/NMSL#39]
老哥你的项目我啦下来跑不起来，似乎是依赖包名没有写入依赖文件中

**Comment by FioraLove** [comment]
> 老哥你的项目我啦下来跑不起来，似乎是依赖包名没有写入依赖文件中

**Comment by FioraLove** [comment]
> 老哥你的项目我啦下来跑不起来，似乎是依赖包名没有写入依赖文件中

 - 程序运行的依赖我应该都导入到 **package.json** ,应该是vue打包到正式环境时在 vue.config 配置了开启图片Gzip压缩时的依赖没有写入package.json，我参考的是这篇文章 [手把手教你深入Vue3.0(Vue-cli4)项目打包性能优化实践](https://blog.csdn.net/qq_36824777/article/details/106407846)
 - 如果不是很明白，加我的秋秋（QQ）：980710425
 - 后端api的项目地址为：https://github.com/FioraLove/Restful-API-Django
 -  Django启动方式：`python manage.py runserver 127.0.0.1:8001`  (映射端口修改的话，vue-cli下的 `src\store\facturl.js` 也要修改)

**Comment by FioraLove** [comment]
@Yu-python

**Comment by FioraLove** [comment]
well done
